### ISSUE TITLE
I want to add two buttons problem from codeforces 

### ISSUE THREAD

**Issue by anj20** [tanus786/CP-Codes-HackOctober-Fest-2022#202]

**Comment by tanus786** [comment]
Sure go for it✌

**Comment by SanjoySaha24** [comment]
I want to contribute @tanus786. Please assign me so that I can complete hacktoberfest 🙏.

**Comment by RP2025** [comment]
@SanjoySaha24  kindly assign me this,I want to contribute to this

**Comment by SanjoySaha24** [comment]
Accept my pull request 🙏 @tanus786.
