### ISSUE TITLE
Segregate even and odd numbers

### ISSUE THREAD

**Issue by jitendrakohar** [tanus786/CP-Codes-HackOctober-Fest-2022#214]
i want to write the program of Segregate even and odd numbers in java @

**Comment by Jyotisaini-2001** [comment]
Hii, I want to contribute the code of Segregate even and odd numbers in cpp please assign me.

**Comment by tanus786** [comment]
sure go for it✌🐱‍🏍

**Comment by jitendrakohar** [comment]
`import java.io.*;
class GFG
{
public static void arrayEvenAndOdd(int arr[], int n)
{
    int[] a;
    a = new int[n];
    int index = 0;
    for (int i = 0; i < n; i++)
    {
        if (arr[i] % 2 == 0)
        {
            a[index] = arr[i];
            index++;
        }
    }
    for (int i = 0; i < n; i++)
    {
        if (arr[i] % 2 != 0)
        {
            a[index] = arr[i];
            index++;
        }
    }
    for (int i = 0; i < n; i++)
    {
        System.out.print(a[i] + " ");
    }
    System.out.println("");
}
    // Driver code
    public static void main (String[] args)
    {
       
      int arr[] = { 1, 3, 2, 4, 7, 6, 9, 10 };
            int n = arr.length;
 
            // Function call
            arrayEvenAndOdd(arr, n);
    }
}
 `

**Comment by Jyotisaini-2001** [comment]
thank you @tanus786. I have added my code.
