### ISSUE TITLE
I want to add codechef solutions kindly assign it to me

### ISSUE THREAD

**Issue by hellovaibhav** [tanus786/CP-Codes-HackOctober-Fest-2022#235]
want to add solutions of some recent problems from the codechef contests

**Comment by tanus786** [comment]
sure go for it😊

**Comment by SanjoySaha24** [comment]
I want to contribute @tanus786. Please assign me so that I can complete hacktoberfest 🙏.

**Comment by tanus786** [comment]
@SanjoySaha24 sure go for it👍
