### ISSUE TITLE
Flatten binary tree into linked list

### ISSUE THREAD

**Issue by kunalkabra46** [tanus786/CP-Codes-HackOctober-Fest-2022#27]
hey @tanus786  i want  to add this issue...

please asisgn me asap...and add hacktoberfest tag

**Comment by tanus786** [comment]
You can directly add the file and make PR I'll merge it. And give this repo a star also✨

**Comment by tanus786** [comment]
Sure..also give this repo a like✨

**Comment by kunalkabra46** [comment]
i have made pull request please look into it...

**Comment by tanus786** [comment]
did you fork the repo?
its not showing any PR on my profile

**Comment by kunalkabra46** [comment]
I have fork the repository and commit the change into main branch and made pull request...

please check and add hacktoberfest accepted label...

**Comment by tanus786** [comment]
done

**Comment by tanus786** [comment]
can you please give me follow back

**Comment by kunalkabra46** [comment]
add same in my pull request also...

**Comment by kunalkabra46** [comment]
> can you please give me follow back

sure...

**Comment by kunalkabra46** [comment]
you can also follow me if don't mind...

**Comment by kunalkabra46** [comment]
> add same in my pull request also...

please do this asap...

**Comment by kunalkabra46** [comment]
and if you don't mind we collab and work together...in CP field as well as in web development...

**Comment by tanus786** [comment]
Sure I'd like to work together.✨

**Comment by tanus786** [comment]
And i think your PR is accepted please check on HackOctober website.

**Comment by kunalkabra46** [comment]
> And i think your PR is accepted please check on HackOctober website.

yaa just checked
