### ISSUE TITLE
Count Number of Distinct Integers After Reverse Operations

### ISSUE THREAD

**Issue by Jyotisaini-2001** [tanus786/CP-Codes-HackOctober-Fest-2022#272]
Hii @tanus786 . I want to add Leetcode medium level contest question "Count Number of Distinct Integers After Reverse Operations" in c++.
Please assign this issue to me.
thank you!!.

**Comment by tanus786** [comment]
Sure go for it😊

**Comment by anshulkumar2311** [comment]
Hii Can you assign this issue with me. As I already solve this problem.

**Comment by anshulkumar2311** [comment]
https://github.com/anshulkumar2311/CP-Codes-HackOctober-Fest-2022/commit/ee2f8341683a939da242cf74e1c0603a6605ad01
