### ISSUE TITLE
Merge Two Binary Search Tree

### ISSUE THREAD

**Issue by anshulkumar2311** [tanus786/CP-Codes-HackOctober-Fest-2022#290]
Hey!! I'm solving this problem with c++. Can you Assign this problem to me. It is Leetcode Hard Problem.

**Comment by tanus786** [comment]
sure go for it😄

**Comment by manvika-10** [comment]
Hii, I want to do this problem in CPP. Can you assign this issue to me?

**Comment by manvika-10** [comment]
Hii, I want to solve this problem in c++. Can you assign this issue to me?

**Comment by tanus786** [comment]
Sure @manvika-10 go for it✨

**Comment by ShrijanaSapkota** [comment]
Hi! I want to solve this problem in python. Can you please assign me this?

**Comment by tanus786** [comment]
Sure go for it @ShrijanaSapkota

**Comment by adithya27082002** [comment]
can i solve this?

**Comment by tanus786** [comment]
Sure go for it @adithya27082002

**Comment by jitendrakohar** [comment]
i also want to contribute here

**Comment by tanus786** [comment]
Sure go for it 👍

**Comment by 1GauravRathore** [comment]
hello , I want to contribute 
can you assign me this problem?

**Comment by tanus786** [comment]
Yeah go for it!!
