### ISSUE TITLE
Aggressive cows problem solution 

### ISSUE THREAD

**Issue by sambhavjain1234** [tanus786/CP-Codes-HackOctober-Fest-2022#322]
i would like to add a leetcode aggressive cows problem in cpp , please kindly assign me this .

**Comment by tanus786** [comment]
sure go for it😊 please give this repo a star also✌

**Comment by anj20** [comment]
hi, @tanus786 can I add the solution to the Aggressive cow problem?

**Comment by tanus786** [comment]
yeah sure go for it✌🐱‍🏍 @anj20

**Comment by manvika-10** [comment]
Hi, Please assign this issue to me.

**Comment by tanus786** [comment]
Okay go for it 
@manvika-10  @sambhavjain1234
