### ISSUE TITLE
Best Time to buy and sell stocks 

### ISSUE THREAD

**Issue by Gaurika-Gupta** [tanus786/CP-Codes-HackOctober-Fest-2022#380]
Solution of the below problems of Best Time to Buy and Sell Stocks of Leetcode in Java.
1. Best Time to Buy and Sell Stock (121)
2. Best Time to Buy and Sell Stock 2 (122)
3. Best Time to Buy and Sell Stock 3 (123)
4. Best Time to Buy and Sell Stock 4 (188)
5. Best Time to Buy and Sell Stock with Cooldown (309)
6. Best Time to Buy and Sell Stock with Transaction Fees (714)

**Comment by Gaurika-Gupta** [comment]
Please assign me this Issue under Hacktoberfest 2022 after adding the necessary labels.

**Comment by tanus786** [comment]
Sure go for it✨👍

**Comment by tanus786** [comment]
Also please give this repo a star and follow me for follow back if your PR got successfully merged 😊
