### ISSUE TITLE
Binary lifting in a tree 

### ISSUE THREAD

**Issue by SumantxD** [tanus786/CP-Codes-HackOctober-Fest-2022#410]
binary lifting is a technique which is used to find the lowest common ancestor of two nodes in a tree in log(n)  time, it is an application of sparse table on trees.  the basic premise of this technique is that instead of linearly iterating on ancestors, we can make a jump of powers of two, and since every no can be written in the terms of sum of power of two, every jump can also be written in terms of sum of power of two.

my implementation involves the concept of OOP where you can create "do the precomputation on that specific tree" just by passing the adjacency list containing that tree, and make queries independently.

**Comment by tanus786** [comment]
okay great issue go for it😊

**Comment by tanus786** [comment]
if this repo helped you please give this a star also.. thank you✌

**Comment by iamAditya01** [comment]
assign me this one dear

**Comment by tanus786** [comment]
Okay bro go for it 👍

**Comment by iamAditya01** [comment]
sure

**Comment by tanus786** [comment]
@iamAditya01 please give this repo a star also. Thank you 😊

**Comment by iamAditya01** [comment]
done ! can we connect on twitter ?

**Comment by iamAditya01** [comment]
completed ! Merge it ;)
