### ISSUE TITLE
I want to add a code to remove duplicates from a sorted linked list.

### ISSUE THREAD

**Issue by TamannaVerma99** [tanus786/CP-Codes-HackOctober-Fest-2022#78]

**Comment by omprakashchhetri** [comment]
Hey can you assign me this issue!

**Comment by TamannaVerma99** [comment]
Hey @tanus786 you have added some labels on this issue ...so have you assigned this issue to me?

**Comment by tanus786** [comment]
Okay I'll assign you both go for it✨👍

**Comment by omprakashchhetri** [comment]
can I use C ?

**Comment by tanus786** [comment]
Sure

**Comment by omprakashchhetri** [comment]
hey I've completed the code can you please guide me, where to add my contribution? @tanus786

**Comment by tanus786** [comment]
Check the readme file or you can simply add it in the repo

**Comment by omprakashchhetri** [comment]
I've added my PR can you please check .
thank you!

**Comment by tanus786** [comment]
i have merge it ✌

**Comment by SanjoySaha24** [comment]
I want to contribute. Please assign it @tanus786   as my first contribution for hacktoberfest 2022.

**Comment by tanus786** [comment]
I have assigned you this issue please give this repo a star and follow me for follow back 😊
